from flask_restful import reqparse

parser_user = reqparse.RequestParser()
parser_user.add_argument("surname", required=True)
parser_user.add_argument("name", required=True)
parser_user.add_argument("age", required=True, type=int)
parser_user.add_argument("position", required=True)
parser_user.add_argument("speciality", required=True)
parser_user.add_argument("address", required=True)
parser_user.add_argument("email", required=True)
parser_user.add_argument("password", required=True)

parser_user_noreq = reqparse.RequestParser()
parser_user_noreq.add_argument("surname")
parser_user_noreq.add_argument("name")
parser_user_noreq.add_argument("age", type=int)
parser_user_noreq.add_argument("position")
parser_user_noreq.add_argument("speciality")
parser_user_noreq.add_argument("address")
parser_user_noreq.add_argument("email")
parser_user_noreq.add_argument("password")


parser_job = reqparse.RequestParser()
parser_job.add_argument("team_leader", required=True, type=int)
parser_job.add_argument("job", required=True)
parser_job.add_argument("work_size", required=True, type=int)
parser_job.add_argument("collaborators", required=True)
parser_job.add_argument("start_date", required=True)
parser_job.add_argument("end_date", required=True)
parser_job.add_argument("is_finished", required=True)

parser_job_noreq = reqparse.RequestParser()
parser_job_noreq.add_argument("team_leader", type=int)
parser_job_noreq.add_argument("job")
parser_job_noreq.add_argument("work_size", type=int)
parser_job_noreq.add_argument("collaborators")
parser_job_noreq.add_argument("start_date")
parser_job_noreq.add_argument("end_date")
parser_job_noreq.add_argument("is_finished")
